#!/usr/bin/env zsh
#
# Copyright (c) 2022 Sebastian Gniazdowski

0=${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}
0=${${(M)0##/*}:-$PWD/$0}
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

# Run as script? ZSH_SCRIPT is a Zsh 5.3 addition
if [[ $0 != */ti::global.zsh || ! -f $0 ]]; then
     if [[ -f $0:h/ti::global.zsh ]]; then
        $Plugins[TIG_DIR]=$0:h:h
        TIG_SUITE_DIR=$Plugins[TIG_DIR]
    elif [[ -f $TIG_SUITE_DIR/libexec/ti::global.zsh ]]; then
        0=$TIG_SUITE_DIR/libexec/ti::global.zsh
        Plugins[TIG_DIR]=$TIG_SUITE_DIR
    elif [[ -f $Plugins[TIG_DIR]/libexec/ti::global.zsh ]]; then
        0=$Plugins[TIG_DIR]/libexec/ti::global.zsh
        TIG_SUITE_DIR=$Plugins[TIG_DIR]
    else
        local -a q=( $Plugins[TIG_DIR] $TIG_SUITE_DIR $0:h:h )
        timsg {204}Error:%f couldn\'t locate {39}Tig Suite\'s%f source \
            directory (tryied in dirs: {27}${(j:%f,{27}:)q}%f), cannot \
            continue.
        return 1
    fi
else
    $Plugins[TIG_DIR]=$0:h:h
    TIG_SUITE_DIR=$Plugins[TIG_DIR]
fi

REPLY=$Plugins[TIG_DIR]
[[ -d $REPLY ]] && REPLY+=/libexec/ti::global.zsh
