#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*# Copyright (c) 2022 Sebastian Gniazdowski
0="${(%):-%x}"

local which=$1 met=$3 obj=$2
local -aU qa

# Initialize
ti::util-verify-tigsuite-dir||return 1
ti::util-verify-cid "$which" $obj||return 1
ti::util-tigsuite-startup rename "" $which-$obj||return 1

preamble-and-files() {
        local tpe=$1 cid=$2 cmd txt
        print ${(r:COLUMNS::—:):-—}
        print -n Showing files gathered for current PWD project
        if [[ $tpe == commit ]];then
            print \ \($PID\) in the commit: ·$cid[1,7]
            cmd=enc
            txt="commit ·$cid[1,7]"
            {qa=(${(@f)"$(command git diff --name-only $cid~..$cid)"});} TIO
        fi
        if [[ $tpe == queue ]];then
            print \ \($PID\) in the queue file:\\n·$TIPID_QUEUE
            txt=accumulator/queue-file
            cmd=enq
            {qa=(${(@f)"$(<$TIPID_QUEUE)"});} TIO
        fi
        print To convert it into a °feature° object press \"$cmd\" \
            in TIG interface
        print ${(r:COLUMNS::—:):-—}
        print \\nFiles in the $txt:\\n
        (($#qa))||qa=("Error: no data obtained")
        printf ·%s\\n $qa
}

if [[ $which == queue ]];then
    if [[ ! -s $TIPID_QUEUE ]];then
        timsg -h %B{204}Notice:%f%b queue is empty, nothing to display…
        return 1
    fi
    local -a arg=($which)
fi
if [[ $which == commit ]];then
    local -a arg=($which $obj)
fi
preamble-and-files $arg|tig
 
 # vim:ft=zsh:tw=80:sw=4:sts=4:et:foldmarker=[[[,]]]
