#!/usr/bin/env zsh
0=${(%):-%x}
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

# Uses $ID, $PID, $PDIR, $TIPID_QUEUE
local q op=$1 qc=$2
local ctxt="NO COMMIT WAS HIGHLIGHTED IN %B{204}TIG-interface"

# Read the var by name – files to be added to feat-$ID
local -a qa=(${(@z)${(PA@)qc}})

# dir, QREGI_FILE 
timsg %B{204}Initial status{135} of the operation ≈ {39}$op{135}:\\n\
{135}· {41}PID{135} – the present PWD project-ID/tag:\
    «[227]{27}${(U)PID}{135}%k»\\n\
%B{135}· Project dir: %U{39}$PDIR%u{135}\\n\
· Registry file path: {69}$QREGI_FILE{135}

# ID
[[ -n $ID ]]&&timsg %B{135}· The name of the °{41}feature{135}° given: \
                «[227]{27}${ID}{135}%k»

# CID
[[ $CID != 0# ]]&&timsg %B{135}· The hovered commit in {205}TIG%f interface: \
                «{27}${CID[1,7]}{135}»

# TIG_SUITE_DIR, PID
timsg %B{135}· {41}$TINICK{135} source directory path: {69}$TIG_SUITE_DIR{135}\
 \\n{135}· Accumulator/queue-file: {39}$TIPID_QUEUE:t{135} of project {41}$PID

# Chooser program
timsg %B{135}· Chooser {33}TUI{135} app to pick °{27}features{135}° to \
    open them: %U{204}${TIFZF_BIN:-(none)}
