#!/usr/bin/env zsh
0="${(%):-%x}"
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

local TMP
# configure fuzzy searcher
[[ -z $TIFZF_BIN ]]&&for TMP in tig-pick fzf fzy; do
    (($+commands[$TMP]))&&: ${TIFZF_BIN:=$TMP}&&break
done
REPLY=$TIFZF_BIN

if [[ ! -x =$TIFZF_BIN ]];then
    local -a q=(tig-pick fzf fzy)
    timsg -h %B{204}Error:%f%b no chooser app found, tried one of:\\n\
%B{39}·${(~j.%f%b, {39}%B·.)q}%f%b,\\nand currently \
${${TIFZF_BIN:+set %B{41}TIFZF_BIN%f%b to: %B{39}$TIFZF_BIN%f%b}:-\
%B{41}TIFZF_BIN%f%b is unset)}
    return 1
fi

return 0