#!/usr/bin/env zsh
0="${(%):-%x}"
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

if [[ ! -d $TIG_SUITE_DIR || ! -f $0 || ! -r $0 ]];then
    timsg -h %U{204}Error:%f cannot find/read %B{204}$TINICK%f%b program \
        directory, wrong or empty {39}\$TIG_SUITE_DIR%f \
        \(set to: {41}${TIG_SUITE_DIR:-(NULL)}%f\)
    return 1
fi

return 0
