#!/usr/bin/env zsh
0="${(%):-%x}"
0="${${(M)0:#/*}:-$PWD/$0}"
: ${TIG_SUITE_DIR:=$0:h:h} ${Plugins[TIG_DIR]:=$0:h:h}

# Input/options
local -A Opts
builtin zparseopts -D -E -A Opts -- || return 1

local FROM=$1 PID_=$2 ID OP QUEUE=$TIPID_QUEUE
local OP=edit-ext-$FROM EDITOR=${EDITOR:-mcedit}

# Initialize
util/ti::verify-tigsuite-dir||return 1
util/ti::tigsuite-startup $OP "" "<empty>"||return 1
util/ti::get-editor||return 1
EDITOR=$REPLY

if [[ $FROM == features ]]; then
    $EDITOR $TINFO
fi
if [[ $FROM == queue ]]; then
    [[ -n $PID_ ]]&&QUEUE=$TICACHE/PID::$PID_.queue||{tigmsg -h {208}Error:%f\
                    PWD is not a project, first {33}cd%f to one, exiting…
                    return 3
                }
    $EDITOR $QUEUE
fi
 